name: Run tests

on:
  pull_request:
    branches: ["*"]
    paths: ["**/*.go", "go.*"]
  push:
    branches: ["*"]
    tags-ignore: ["v*"]
    paths: ["**/*.go", "go.*"]
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests
        uses: robherley/go-test-action@v0
